clear all
close all
clc

%%%%%%%%%%%%%%%%%%%%%%%%% GA Definition %%%%%%%%%%%%%%%%%%%%%%%%%
lowerboundof_k = [-1000 -1000 -1000];  % Bounds for [Kp Ki Kd]
upperboundof_k = [1000 1000 1000];
num_variables = 3;

fitness_fun = @(k) Fitness_Function(k);

opt = gaoptimset(...
    'PopulationSize', 150, ...
    'Generations', 200, ...
    'CrossoverFraction', 0.8, ...
    'EliteCount', 2, ...
    'MutationFcn', {@mutationadaptfeasible, 0.8}, ...
    'SelectionFcn', @selectionroulette, ...
    'Display', 'iter', ...
    'PlotFcns', {@gaplotbestf, @gaplotstopping, @gaplotbestindiv}, ...
    'TolFun', 1e-6);

[PID_gain, optvalu1] = ga(fitness_fun, num_variables, [], [], [], [], ...
    lowerboundof_k, upperboundof_k, [], opt);

% Correctly print PID gains (Kp, Ki, Kd)
fprintf('\nOptimal PID gains:\nKp = %.4f\nKi = %.4f\nKd = %.4f\n', ...
    PID_gain(1), PID_gain(2), PID_gain(3));

fprintf('Best ITAE cost: %.4f\n', optvalu1);
